# Generated by Django 5.2.9 on 2025-12-11 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(help_text='Código interno único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, help_text='EAN-13, UPC o código interno', max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de costo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de venta')),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('box', 'Caja'), ('pack', 'Paquete')], default='unit', max_length=10, verbose_name='Unidad de medida')),
                ('min_stock', models.PositiveIntegerField(default=10, help_text='Nivel de alerta para stock bajo', verbose_name='Stock mínimo')),
                ('max_stock', models.PositiveIntegerField(default=100, help_text='Nivel máximo sugerido de stock', verbose_name='Stock máximo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_sellable', models.BooleanField(default=True, verbose_name='Disponible para venta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bajo'), ('out_of_stock', 'Sin stock'), ('overstock', 'Exceso de stock'), ('expiring', 'Por vencer')], max_length=20, verbose_name='Tipo de alerta')),
                ('threshold', models.PositiveIntegerField(help_text='Cantidad que activa la alerta', verbose_name='Umbral')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificar por email')),
            ],
            options={
                'verbose_name': 'Alerta de stock',
                'verbose_name_plural': 'Alertas de stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('movement_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('transfer_in', 'Transferencia entrada'), ('transfer_out', 'Transferencia salida'), ('adjustment_in', 'Ajuste entrada'), ('adjustment_out', 'Ajuste salida'), ('return_customer', 'Devolución cliente'), ('return_supplier', 'Devolución proveedor'), ('damage', 'Daño/Pérdida'), ('initial', 'Inventario inicial')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(help_text='Positivo para entradas, negativo para salidas', verbose_name='Cantidad')),
                ('previous_quantity', models.IntegerField(verbose_name='Cantidad anterior')),
                ('new_quantity', models.IntegerField(verbose_name='Cantidad nueva')),
                ('reference', models.CharField(blank=True, help_text='Número de factura, orden, etc.', max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('quantity', models.IntegerField(default=0, help_text='Stock actual disponible', verbose_name='Cantidad')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Cantidad reservada para órdenes pendientes', verbose_name='Cantidad reservada')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='branches.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Stock de sucursal',
                'verbose_name_plural': 'Stock de sucursales',
            },
        ),
    ]
