# Generated by Django 5.2.9 on 2025-12-11 17:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('employees', '0001_initial'),
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('receive_low_stock', models.BooleanField(default=True, verbose_name='Recibir alertas de stock bajo')),
                ('receive_out_of_stock', models.BooleanField(default=True, verbose_name='Recibir alertas de sin stock')),
                ('receive_cash_difference', models.BooleanField(default=True, verbose_name='Recibir alertas de diferencia de caja')),
                ('receive_void_alerts', models.BooleanField(default=True, verbose_name='Recibir alertas de anulaciones')),
                ('receive_shift_alerts', models.BooleanField(default=True, verbose_name='Recibir alertas de turnos')),
                ('receive_system_alerts', models.BooleanField(default=True, verbose_name='Recibir alertas del sistema')),
                ('minimum_severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='low', help_text='Solo recibir alertas de esta severidad o mayor', max_length=20, verbose_name='Severidad mínima')),
                ('email_digest', models.BooleanField(default=False, help_text='Enviar resumen diario en lugar de alertas individuales', verbose_name='Resumen por email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de alertas',
                'verbose_name_plural': 'Preferencias de alertas',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bajo'), ('out_of_stock', 'Sin stock'), ('overstock', 'Exceso de stock'), ('cash_difference', 'Diferencia de caja'), ('high_void_rate', 'Alta tasa de anulaciones'), ('sales_anomaly', 'Anomalía en ventas'), ('shift_overtime', 'Turno extendido'), ('system', 'Sistema')], max_length=30, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Severidad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='active', max_length=20, verbose_name='Estado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del tipo de alerta', verbose_name='Metadatos')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='branches.branch', verbose_name='Sucursal')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='employees.employee', verbose_name='Empleado')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='inventory.product', verbose_name='Producto')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_read', to=settings.AUTH_USER_MODEL, verbose_name='Leída por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', '-created_at'], name='alerts_aler_alert_t_b7affd_idx'), models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'), models.Index(fields=['severity', '-created_at'], name='alerts_aler_severit_f1bbe4_idx'), models.Index(fields=['branch', '-created_at'], name='alerts_aler_branch__2be6e3_idx'), models.Index(fields=['is_read', '-created_at'], name='alerts_aler_is_read_be931c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('branch', 'Por sucursal'), ('category', 'Por categoría')], default='global', max_length=20, verbose_name='Alcance')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Porcentaje del stock mínimo configurado en producto', verbose_name='Umbral stock bajo')),
                ('overstock_threshold', models.PositiveIntegerField(default=150, help_text='Porcentaje del stock máximo configurado en producto', verbose_name='Umbral exceso de stock')),
                ('cash_difference_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Diferencia mínima para generar alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Umbral diferencia de caja')),
                ('void_rate_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje de anulaciones para generar alerta', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Umbral tasa de anulaciones (%)')),
                ('overtime_threshold', models.DecimalField(decimal_places=1, default=Decimal('10.0'), help_text='Horas de turno para generar alerta de turno extendido', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Umbral horas extra')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('dashboard_notifications', models.BooleanField(default=True, verbose_name='Notificaciones en dashboard')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='branches.branch', verbose_name='Sucursal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Configuración de alertas',
                'verbose_name_plural': 'Configuraciones de alertas',
                'unique_together': {('scope', 'branch'), ('scope', 'category')},
            },
        ),
    ]
