# Generated by Django 5.2.9 on 2025-12-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
        ("branches", "0004_add_company_fk"),
        ("companies", "0003_create_subscriptions_for_existing_companies"),
        ("employees", "0001_initial"),
        ("inventory", "0003_add_company_fk"),  # Don't depend on price conversion
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_alert_t_b7affd_idx",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_status_e70a14_idx",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_severit_f1bbe4_idx",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_is_read_be931c_idx",
        ),
        migrations.AddField(
            model_name="alert",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="companies.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_configurations",
                to="companies.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "-created_at"], name="alerts_aler_company_9c9ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "alert_type", "-created_at"],
                name="alerts_aler_company_0ac807_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "status", "-created_at"],
                name="alerts_aler_company_14c9a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "severity", "-created_at"],
                name="alerts_aler_company_eb8cf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "is_read", "-created_at"],
                name="alerts_aler_company_0f6a1b_idx",
            ),
        ),
    ]
