# Generated by Django 5.2.9 on 2025-12-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_add_company_multi_tenant"),
        ("branches", "0004_add_company_fk"),
        ("companies", "0003_create_subscriptions_for_existing_companies"),
        ("employees", "0001_initial"),
        ("inventory", "0004_convert_prices_to_cop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="companies.subscription",
                verbose_name="Suscripción",
            ),
        ),
        migrations.AddField(
            model_name="useralertpreference",
            name="receive_subscription_alerts",
            field=models.BooleanField(
                default=True, verbose_name="Recibir alertas de suscripciones"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Stock bajo"),
                    ("out_of_stock", "Sin stock"),
                    ("overstock", "Exceso de stock"),
                    ("cash_difference", "Diferencia de caja"),
                    ("high_void_rate", "Alta tasa de anulaciones"),
                    ("sales_anomaly", "Anomalía en ventas"),
                    ("shift_overtime", "Turno extendido"),
                    ("system", "Sistema"),
                    ("subscription_payment_due", "Pago próximo"),
                    ("subscription_overdue", "Pago vencido"),
                    ("subscription_trial_ending", "Prueba por terminar"),
                    ("subscription_cancelled", "Suscripción cancelada"),
                    ("subscription_suspended", "Suscripción suspendida"),
                    ("new_subscription", "Nueva suscripción"),
                    ("subscription_plan_changed", "Cambio de plan"),
                ],
                max_length=30,
                verbose_name="Tipo de alerta",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type", "status", "-created_at"],
                name="alerts_aler_alert_t_c1fe3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["subscription", "-created_at"],
                name="alerts_aler_subscri_d314bc_idx",
            ),
        ),
    ]
