# Generated by Django 5.2.9 on 2025-12-19 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_add_subscription_alerts"),
        ("branches", "0006_enforce_company_required"),
        ("companies", "0004_user_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Stock bajo"),
                    ("out_of_stock", "Sin stock"),
                    ("overstock", "Exceso de stock"),
                    ("cash_difference", "Diferencia de caja"),
                    ("high_void_rate", "Alta tasa de anulaciones"),
                    ("sales_anomaly", "Anomalía en ventas"),
                    ("shift_overtime", "Turno extendido"),
                    ("system", "Sistema"),
                    ("subscription_payment_due", "Pago próximo"),
                    ("subscription_overdue", "Pago vencido"),
                    ("subscription_trial_ending", "Prueba por terminar"),
                    ("subscription_cancelled", "Suscripción cancelada"),
                    ("subscription_suspended", "Suscripción suspendida"),
                    ("new_subscription", "Nueva suscripción"),
                    ("subscription_plan_changed", "Cambio de plan"),
                    ("high_churn_rate", "Alta tasa de cancelaciones"),
                    ("revenue_anomaly", "Anomalía en ingresos"),
                    ("low_platform_activity", "Baja actividad en plataforma"),
                    ("tenant_limit_approaching", "Tenant cerca del límite"),
                    ("tenant_inactive", "Tenant inactivo"),
                    ("onboarding_stalled", "Onboarding detenido"),
                    ("high_error_rate", "Alta tasa de errores"),
                    ("system_performance", "Rendimiento del sistema"),
                ],
                max_length=30,
                verbose_name="Tipo de alerta",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("product_created", "Producto creado"),
                            ("product_updated", "Producto modificado"),
                            ("product_deleted", "Producto eliminado"),
                            ("stock_adjusted", "Ajuste de stock"),
                            ("stock_transferred", "Transferencia de stock"),
                            ("sale_created", "Venta realizada"),
                            ("sale_voided", "Venta anulada"),
                            ("cash_register_opened", "Caja abierta"),
                            ("cash_register_closed", "Caja cerrada"),
                            ("employee_created", "Empleado creado"),
                            ("employee_updated", "Empleado modificado"),
                            ("shift_started", "Turno iniciado"),
                            ("shift_ended", "Turno finalizado"),
                            ("branch_created", "Sucursal creada"),
                            ("branch_updated", "Sucursal modificada"),
                            ("user_created", "Usuario creado"),
                            ("user_updated", "Usuario modificado"),
                            ("role_changed", "Rol cambiado"),
                            ("supplier_created", "Proveedor creado"),
                            ("supplier_updated", "Proveedor modificado"),
                            ("purchase_order_created", "Orden de compra creada"),
                        ],
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventario"),
                            ("sales", "Ventas"),
                            ("employees", "Empleados"),
                            ("branches", "Sucursales"),
                            ("users", "Usuarios"),
                            ("suppliers", "Proveedores"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=300, verbose_name="Nombre del usuario"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del modelo afectado (ej: Product, Sale)",
                        max_length=50,
                        verbose_name="Tipo de objeto",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del objeto"
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo del objeto afectado",
                        max_length=255,
                        verbose_name="Nombre del objeto",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales como cambios realizados, valores anteriores/nuevos",
                        verbose_name="Metadatos",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Leído"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="branches.branch",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leído por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de actividad",
                "verbose_name_plural": "Registros de actividad",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="alerts_acti_company_dfc17c_idx",
                    ),
                    models.Index(
                        fields=["company", "module", "-created_at"],
                        name="alerts_acti_company_18192b_idx",
                    ),
                    models.Index(
                        fields=["company", "is_read", "-created_at"],
                        name="alerts_acti_company_9b2632_idx",
                    ),
                    models.Index(
                        fields=["company", "user", "-created_at"],
                        name="alerts_acti_company_7050fb_idx",
                    ),
                ],
            },
        ),
    ]
