# Generated by Django 5.2.9 on 2025-12-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial_company_model'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL para SuperAdmin de plataforma', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Puede gestionar toda su empresa', verbose_name='Admin de empresa'),
        ),
    ]
