# Generated by Django 5.2.9 on 2025-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_company_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_roles',
            field=models.BooleanField(default=True, help_text='Permite crear nuevos roles (solo editar si es False)', verbose_name='Puede crear roles'),
        ),
    ]
