# Generated by Django 5.2.9 on 2025-12-17 14:30

import django.db.models.deletion
from django.db import migrations, models


def assign_company_to_roles(apps, schema_editor):
    """
    Data migration: Assign each role to the company of users who have that role.
    Roles without users remain as global (company=NULL).
    """
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')

    for role in Role.objects.all():
        # Find first user with this role that has a company
        user_with_company = User.objects.filter(
            role=role,
            company__isnull=False
        ).first()

        if user_with_company:
            role.company = user_with_company.company
            role.save(update_fields=['company'])


def reverse_assign_company(apps, schema_editor):
    """Reverse: Remove company assignment from all roles."""
    Role = apps.get_model('users', 'Role')
    Role.objects.all().update(company=None)


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_create_subscriptions_for_existing_companies"),
        ("users", "0003_add_can_create_roles"),
    ]

    operations = [
        # Step 1: Add nullable company FK
        migrations.AddField(
            model_name="role",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece el rol. NULL para roles globales (SuperAdmin).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="companies.company",
                verbose_name="Empresa",
            ),
        ),
        # Step 2: Assign companies to existing roles based on user ownership
        migrations.RunPython(assign_company_to_roles, reverse_assign_company),
        # Step 3: Remove unique constraint on name alone
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        # Step 4: Add unique constraint per company
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_role_name_per_company"
            ),
        ),
    ]
