# Generated by Django 5.2.9 on 2025-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_company_to_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Forzar cambio de contraseña en el próximo inicio de sesión",
                verbose_name="Debe cambiar contraseña",
            ),
        ),
    ]
