# Generated by Django 5.2.9 on 2025-12-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("supervisor", "Supervisor"),
                    ("employee", "Empleado"),
                    ("cashier", "Cajero"),
                    ("warehouse", "Almacenista"),
                    ("viewer", "Solo Lectura"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Tipo de rol",
            ),
        ),
    ]
