# Generated by Django 5.2.9 on 2025-12-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_add_employee_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=True,
                help_text="El email ha sido verificado. False para usuarios nuevos creados por admin.",
                verbose_name="Email verificado",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código de 6 dígitos para verificación",
                        max_length=6,
                        verbose_name="Código",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del código",
                        verbose_name="Expira en",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de intentos fallidos de verificación",
                        verbose_name="Intentos",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="El código ya fue utilizado",
                        verbose_name="Usado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de verificación",
                "verbose_name_plural": "Códigos de verificación",
                "db_table": "email_verification_codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
