# Generated by Django 5.2.9 on 2025-12-11 14:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('ordered', 'Ordenada'), ('partial', 'Parcialmente recibida'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Fecha de orden')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='Cantidad ordenada')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Cantidad recibida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item de orden de compra',
                'verbose_name_plural': 'Items de orden de compra',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único del proveedor', max_length=20, unique=True, verbose_name='Código')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('tax_id', models.CharField(blank=True, help_text='Identificación fiscal', max_length=20, verbose_name='RFC/NIT')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('payment_terms', models.PositiveIntegerField(default=30, help_text='Días de crédito', verbose_name='Plazo de pago (días)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Límite de crédito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
