# Generated by Django 5.2.9 on 2025-12-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial_company_model'),
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company', verbose_name='Empresa'),
        ),
    ]
