# Generated by Django 5.2.9 on 2025-12-16 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_create_subscriptions_for_existing_companies'),
        ('suppliers', '0003_add_company_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(help_text='Código único del proveedor por empresa', max_length=20, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_supplier_code_per_company'),
        ),
    ]
