# Generated by Django 5.2.9 on 2025-12-11 15:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        help_text="Identificador único del empleado",
                        max_length=20,
                        unique=True,
                        verbose_name="Código de empleado",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Tiempo completo"),
                            ("part_time", "Medio tiempo"),
                            ("contract", "Por contrato"),
                            ("temporary", "Temporal"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Tipo de empleo",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Título del puesto de trabajo",
                        max_length=100,
                        verbose_name="Puesto",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de contratación")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de terminación"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salario mensual",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Salario",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Para cálculo de horas extra",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tarifa por hora",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de emergencia"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificación fiscal",
                        max_length=20,
                        verbose_name="RFC/CURP",
                    ),
                ),
                (
                    "social_security_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Número de seguro social",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("on_leave", "De licencia"),
                            ("terminated", "Terminado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="branches.branch",
                        verbose_name="Sucursal asignada",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("clock_in", models.DateTimeField(verbose_name="Hora de entrada")),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de salida"
                    ),
                ),
                (
                    "break_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de descanso"
                    ),
                ),
                (
                    "break_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de descanso"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Horas totales",
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Horas de descanso",
                    ),
                ),
                (
                    "worked_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Horas trabajadas",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "is_manual_entry",
                    models.BooleanField(
                        default=False,
                        help_text="Si fue registrado manualmente por un supervisor",
                        verbose_name="Entrada manual",
                    ),
                ),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajustado por",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Sucursal donde se registró el turno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="branches.branch",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="employees.employee",
                        verbose_name="Empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ["-clock_in"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_code"], name="employees_e_employe_f8cfea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["branch", "status"], name="employees_e_branch__045d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["status", "-hire_date"], name="employees_e_status_2d7863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["employee", "-clock_in"], name="employees_s_employe_1c7210_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["branch", "-clock_in"], name="employees_s_branch__c17c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["-clock_in"], name="employees_s_clock_i_7164ce_idx"
            ),
        ),
    ]
