# Generated by Django 5.2.9 on 2025-12-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_enforce_company_required"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Puede asignarse después de crear el empleado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="branches.branch",
                verbose_name="Sucursal asignada",
            ),
        ),
    ]
