# Generated by Django 5.2.9 on 2025-12-12 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de empresa')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly (ej: mi-empresa)', max_length=100, unique=True, verbose_name='Identificador único')),
                ('legal_name', models.CharField(blank=True, max_length=300, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=20, verbose_name='RFC')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Color hexadecimal (ej: #2563eb)', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#64748b', max_length=7, verbose_name='Color secundario')),
                ('email', models.EmailField(max_length=254, verbose_name='Email corporativo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Empresarial')], default='free', max_length=20, verbose_name='Plan')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='Máximo de sucursales')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de usuarios')),
                ('max_products', models.PositiveIntegerField(default=100, verbose_name='Máximo de productos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='companies_slug_e0676c_idx'), models.Index(fields=['is_active', '-created_at'], name='companies_is_acti_7a0b23_idx')],
            },
        ),
    ]
