# Generated by Django 5.2.9 on 2025-12-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial_company_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Gratuito"),
                            ("basic", "Básico"),
                            ("professional", "Profesional"),
                            ("enterprise", "Empresarial"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Prueba"),
                            ("active", "Activa"),
                            ("past_due", "Vencida"),
                            ("cancelled", "Cancelada"),
                            ("suspended", "Suspendida"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("annual", "Anual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Ciclo de facturación",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próximo pago"
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de prueba"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "db_table": "subscriptions",
            },
        ),
    ]
