# Generated by Django 5.2.9 on 2025-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_create_subscriptions_for_existing_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensual"),
                    ("quarterly", "Trimestral"),
                    ("semiannual", "Semestral"),
                    ("annual", "Anual"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="Ciclo de facturación",
            ),
        ),
    ]
