# Generated by Django 5.2.9 on 2025-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único de la sucursal (ej: SUC001)', max_length=20, unique=True, verbose_name='Código')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('manager_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del gerente')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del gerente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_main', models.BooleanField(default=False, help_text='Indica si es la sucursal principal/matriz', verbose_name='Sucursal principal')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
    ]
