# Generated by Django 5.2.9 on 2025-12-12 14:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#f59e0b",
                help_text="Color de acento para destacar elementos",
                max_length=7,
                verbose_name="Color de acento",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="currency",
            field=models.CharField(
                default="MXN",
                help_text="Código de moneda ISO 4217 (ej: MXN, USD, EUR)",
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="currency_symbol",
            field=models.CharField(
                default="$",
                help_text="Símbolo a mostrar antes de los precios",
                max_length=5,
                verbose_name="Símbolo de moneda",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Icono de la pestaña del navegador (recomendado: 32x32px)",
                null=True,
                upload_to="branches/favicons/",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo de la tienda (recomendado: 200x200px)",
                null=True,
                upload_to="branches/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="primary_color",
            field=models.CharField(
                default="#2563eb",
                help_text="Color principal en formato hexadecimal (ej: #2563eb)",
                max_length=7,
                verbose_name="Color primario",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="receipt_footer",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece en la parte inferior de los recibos (ej: políticas de devolución)",
                verbose_name="Pie de recibo",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="receipt_header",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece en la parte superior de los recibos",
                verbose_name="Encabezado de recibo",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="secondary_color",
            field=models.CharField(
                default="#64748b",
                help_text="Color secundario en formato hexadecimal",
                max_length=7,
                verbose_name="Color secundario",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="store_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre comercial que se muestra en la interfaz",
                max_length=150,
                verbose_name="Nombre de la tienda",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("16.00"),
                help_text="Porcentaje de impuesto aplicado a las ventas",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Tasa de impuesto (%)",
            ),
        ),
    ]
