# Generated by Django 5.2.9 on 2025-12-17 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0004_add_company_fk"),
        ("companies", "0003_create_subscriptions_for_existing_companies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="code",
            field=models.CharField(
                help_text="Código único de la sucursal por empresa (ej: SUC001)",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_branch_code_per_company"
            ),
        ),
    ]
