# Generated by Django 5.2.9 on 2025-12-19 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0004_user_reports"),
        ("employees", "0002_make_branch_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inventario", "Inventario"),
                            ("empleados", "Empleados"),
                            ("sucursales", "Sucursales"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En revisión"),
                            ("resuelto", "Resuelto"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "assign_to_all",
                    models.BooleanField(default=False, verbose_name="Asignar a todos"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de revisión"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de resolución"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notas de resolución"
                    ),
                ),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_reports",
                        to="employees.employee",
                        verbose_name="Empleados asignados",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resuelto por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Usuario",
                "verbose_name_plural": "Reportes de Usuario",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="reports_use_company_4252c9_idx",
                    ),
                    models.Index(
                        fields=["company", "status", "-created_at"],
                        name="reports_use_company_c6ff4e_idx",
                    ),
                    models.Index(
                        fields=["company", "category", "-created_at"],
                        name="reports_use_company_efa3d1_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="reports_use_created_35f964_idx",
                    ),
                ],
            },
        ),
    ]
