# Generated by Django 5.2.9 on 2025-12-11 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('sale_number', models.CharField(help_text='Identificador único de la transacción', max_length=30, unique=True, verbose_name='Número de venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% Descuento')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad entregada por el cliente', max_digits=12, verbose_name='Monto recibido')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cambio devuelto al cliente', max_digits=12, verbose_name='Cambio')),
                ('payment_reference', models.CharField(blank=True, help_text='Número de tarjeta (últimos 4), referencia de transferencia, etc.', max_length=100, verbose_name='Referencia de pago')),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('voided', 'Anulada'), ('refunded', 'Reembolsada')], default='completed', max_length=20, verbose_name='Estado')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('void_reason', models.TextField(blank=True, verbose_name='Razón de anulación')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio de venta al momento de la transacción', max_digits=10, verbose_name='Precio unitario')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Costo al momento de la transacción (para cálculo de ganancia)', max_digits=10, verbose_name='Precio de costo')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('product_name', models.CharField(help_text='Nombre capturado al momento de la venta', max_length=200, verbose_name='Nombre del producto')),
                ('product_sku', models.CharField(help_text='SKU capturado al momento de la venta', max_length=50, verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Item de venta',
                'verbose_name_plural': 'Items de venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de apertura')),
                ('opened_at', models.DateTimeField(verbose_name='Hora de apertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de cierre')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Apertura + ventas en efectivo', max_digits=12, verbose_name='Monto esperado')),
                ('cash_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total ventas en efectivo')),
                ('card_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total ventas con tarjeta')),
                ('transfer_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total transferencias')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia entre monto esperado y cierre', max_digits=12, verbose_name='Diferencia')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='branches.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Caja diaria',
                'verbose_name_plural': 'Cajas diarias',
                'ordering': ['-date'],
            },
        ),
    ]
