# Generated by Django 5.2.9 on 2025-12-11 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashregister',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers_closed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='dailycashregister',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers_opened', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_cashier', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_voided', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venta'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycashregister',
            unique_together={('branch', 'date')},
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='sales_sale_sale_nu_99d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-created_at'], name='sales_sale_branch__97dba9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', '-created_at'], name='sales_sale_cashier_62c037_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-created_at'], name='sales_sale_status_c95ece_idx'),
        ),
    ]
